Ea alert block
asu-ke-web-services/UDS-WordPress-Theme pull request #150
Opened 2021-03-16 00:44 UTC by earlalex

Replace this text with a description of the pull request. If you are adding or enhancing functionality, briefly explain what you hope to add or improve. If you are fixing a bug, explain the original problem (and link to an Issue # if there is one). Try to keep it as concise as possible, but make sure you clearly explain the nature of the request.

Changes proposed in this pull request:

- Replace these bullet list items with specific features
- Or details of bug fixes
- Think of them as the 'highlights' of the pull request
- Anything that will help someone who is reviewing the code, or searching the project history

2021-04-06 00:43 UTC, wmcconnell commented
Updated branch now uses the built-in Alert functionality of Bootstrap - including fading out when closed.

2021-04-08 23:36 UTC, zainabD commented
Good job Earl and Walt, I just noticed few things here: 
- [ ] The alert icon show on the top of the box, while in the xd it seems to be vertically at the middle: 

![image](https://user-images.githubusercontent.com/15880606/114108567-2cd40a00-9888-11eb-8b64-261d1f603719.png)

![image](https://user-images.githubusercontent.com/15880606/114108576-32c9eb00-9888-11eb-8033-8168cb97b842.png)

- [ ] Also the space to the left of the "x" button on mobile doesn't look right: 
![image](https://user-images.githubusercontent.com/15880606/114108618-46755180-9888-11eb-8102-906b5beaeace.png)

- [ ] The additional CSS class field is not connected to the markup: 
![image](https://user-images.githubusercontent.com/15880606/114108641-568d3100-9888-11eb-8aa2-e63fc25eab8f.png)

Can we make sure that none of these updates will break our current websites like **devils drop off** and **RTO** ..

2021-04-09 21:47 UTC, zainabD requested changes
I tested this on RTO locally, it looks good, didn't break anything. 

- [ ] The **Additional css classes** field still needs to be connected. 
- [ ] and I think that the "x" button need to stay on the corner. 

Good job on moving the icon to always be at the middle.

2021-04-13 21:06 UTC, zainabD approved these changes

2021-04-13 21:37 UTC, merged