Updated core/separator block
asu-ke-web-services/UDS-WordPress-Theme pull request #186
Opened 2021-04-23 21:22 UTC by zainabD

In this pull request, I updated the native block(core/separator), removed the unwanted (**wide** and **dots**) styles, and added the uds gold style.
Per our last discussion (Walt and I), we decided that we need the other petern's dividers that show in storybook [morse-code-white, morse-code-black, topo-white, topo-black, network-white and network-black], as we can use the background section block instead.

![image](https://user-images.githubusercontent.com/15880606/115930944-2aa0ac80-a43f-11eb-8d85-1788f2f4808f.png)

2021-04-23 21:38 UTC, zainabD commented
This should fix the issue #147

2021-04-23 23:22 UTC, wmcconnell requested changes
Everything seems to work, but the gold divider has no top/bottom margin in the Gutenberg editor (looks fine on the page), and sits right on top of whatever is below it (see screen shot). I think it's the result of removing the margins to prevent the existing `auto` margins from always centering things.


-- Screen shot --
<img width="874" alt="Screen Shot 2021-04-23 at 4 16 01 PM" src="https://user-images.githubusercontent.com/31013359/115938520-d18d4480-a44f-11eb-82ce-bf98eaf09ba2.png">

2021-04-23 23:22 UTC, wmcconnell commented on sass/theme/_theme.scss
> +	margin: 0;
I think this line might be the issue with how the gold divider looks in the editor. Setting all margins to 0 removes the built-in 48px top/bottom that the default divider has. Could we get away with only setting `margin-right` and `margin-left` here?

2021-04-26 22:27 UTC, wmcconnell approved these changes
Approving this with the caveat that we may need to go back and look at how we're enqueuing our block styles, as I think the style preview issue may be related to that.

2021-04-26 22:27 UTC, merged