Add hooks: after_header, before_footer and before_footer_columns
asu-ke-web-services/UDS-WordPress-Theme pull request #55
Opened 2020-11-10 05:50 UTC by SteveRyan-ASU

Proof of concept for the issue raised in #54 a moment ago. The following three lines of code should have no outward effect on the parent theme itself. However, within a child theme, that would allow for a developer to do something like the following in the child theme's `functions.php` 
```
/** 
 * Adds a section of content right above the global footer.
 */
function uds_furi_add_symposium_totals() {
	get_template_part( 'templates/snapshot', 'footer' );
}
add_action( 'uds_wp_before_global_footer', 'uds_furi_add_symposium_totals' );
``` 

... which would look for `/templates/snapshot-footer.php` and execute whatever that code might be immediately before outputting the footer.

2020-11-10 05:53 UTC, SteveRyan-ASU commented
I'll mention the alternative here would be for me to copy the existing `footer.php` from the parent theme into the child theme and add the `get_template_part()` call in the correct place. 

The obvious benefit to having a hook available is that the hook allows for the parent's `footer.php` to be updated without the need to also update the code in the child theme.

2020-11-10 14:20 UTC, nathan-rollins requested changes
I think this is a fantastic idea, and these are great examples for the rest of the team to keep in mind for extension opportunities elsewhere in the theme.

That said, I do have a request: please write up documentation notes in the README for this.

We need to improve our new feature pipeline to include proper documentation in the README at the time of new feature additions. We should actually make this a requirement of all our new feature PRs, they can't be closed out without appropriate documentation for end users or devs being included.

It is important that we include details about why hooks are included, and what each hook allows a theme developer to do (maybe a table of function names with file and line number and brief description?)

2020-11-13 00:26 UTC, nathan-rollins approved these changes

2020-11-13 00:26 UTC, nathan-rollins commented
I am assuming this PR is ready for re-review, since the README is updated and looks pretty good. Nice job!

2020-11-13 00:27 UTC, merged